/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ali
 */
public class NewJFrame_FORMULARIO extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame_FORMULARIO
     */
    public NewJFrame_FORMULARIO() {
        initComponents();
        //CODIGO PARA CENTRAR LA PANTALLA
        this.setLocationRelativeTo(null);
        //codigo para acomodar la imagen
        ImageIcon fondo = new ImageIcon("src/at_marceline__hair___by_michelle_lennon9-d6j0cg1.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(fondoo.getWidth(), fondoo.getHeight(),Image.SCALE_DEFAULT));
         fondoo.setIcon(icono);
           this.repaint();
         
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextAp = new javax.swing.JTextField();
        jTextAm = new javax.swing.JTextField();
        jTextPn = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1procesar = new javax.swing.JButton();
        jButton3limpiar = new javax.swing.JButton();
        jButton2salir = new javax.swing.JButton();
        fondoo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("datos del formulario");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 430, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Kristen ITC", 0, 12)); // NOI18N
        jPanel1.setOpaque(false);

        jTextPn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextAp)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jTextPn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(110, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextAm, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTextAp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jTextPn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jTextAm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 300));

        jPanel5.setOpaque(false);

        jButton1procesar.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jButton1procesar.setText("crear");
        jButton1procesar.setOpaque(false);
        jButton1procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1procesarActionPerformed(evt);
            }
        });

        jButton3limpiar.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jButton3limpiar.setText("limpiar");
        jButton3limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3limpiarActionPerformed(evt);
            }
        });

        jButton2salir.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jButton2salir.setText("Salir");
        jButton2salir.setOpaque(false);
        jButton2salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton1procesar)
                .addGap(18, 18, 18)
                .addComponent(jButton3limpiar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton2salir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(jButton1procesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 230, 100));

        fondoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arte-digital-martina-stipan-1.jpg"))); // NOI18N
        getContentPane().add(fondoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 620, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1procesarActionPerformed
       //declarar variables
        String jLabel2, jLabel3, jLabel4,jLabel5 ;
          jLabel2 = jTextAp.getText();
           jLabel3 = jTextAm.getText();
           jLabel4 = jTextPn.getText();
          
           //codigo para dtos generales
           if (jTextAp.getText().equals("")) {
               JOptionPane.showMessageDialog(null,"porfavor ingrese su apellido paterno");
            return;
        }
           if (jTextAm.getText().equals("")) {
               JOptionPane.showMessageDialog(null,"porfavor ingrese su apellido materno");
            return; 
           }
               if (jTextPn.getText().equals("")) {
               JOptionPane.showMessageDialog(null,"porfavor ingrese su primer nombre");
            return;
    }
             
       //CODIGO PARA EL GRUPO SEXO
  
   
              //CODIGO PARA EL ESTADO CIVIL
              
               
               //CODIGO PARA VISUALIZAR LOS RESULTADOS EN EL FORMULARIO 2
               
               
               //CODIGO PARA  EVITAR SELECCIONAR AMBOS ESTADOS CIVILES
         
               
               //CODIGO PRA LLAMAR AL SEGUNDO FORMULARIO
                NewJFrame_FORMULARIO2 FORM2 = new NewJFrame_FORMULARIO2();
                FORM2.setVisible(true);
                
              //CODIGO PARA OCULTAR EL FORMULARIO PESENTE
                this.setVisible(false);
               
                //CODIGO PARA VISUALIZAR LOS  DATOS GENERALES
                
               FORM2.jLabel2nomb4.setText(""+jLabel4);
              
               FORM2.jLabel2apellidopaterno.setText(""+jLabel2);
               FORM2.jLabel2apellidoM.setText(""+jLabel3);
             
               //CODIGO PARA MOSTRAR LA RESPUESTA DEL SEGUNDO NOMBRE
             
               //CODIGO PARA EL SEXO
                
               
               
             
    }//GEN-LAST:event_jButton1procesarActionPerformed
           
    private void jButton3limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3limpiarActionPerformed
       //CODIGO PARA LIMPIAR DATOS GENERALES
        jTextAp.setText("");
        jTextAm.setText("");
        jTextPn.setText("");
     
        //CODIGO PARA EL LIMPIAR EL GRUPO SEXO
      
           
           //CODIGO PARA LIMPIAR EL ESTADO CIVIL
        
        
        
           
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3limpiarActionPerformed

    private void jButton2salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2salirActionPerformed
        // CODIGO PARA SALIR
        System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2salirActionPerformed

    private void jTextPnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPnActionPerformed
          
    
    
    /**.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame_FORMULARIO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1sexo;
    private javax.swing.JLabel fondoo;
    private javax.swing.JButton jButton1procesar;
    private javax.swing.JButton jButton2salir;
    private javax.swing.JButton jButton3limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextAm;
    private javax.swing.JTextField jTextAp;
    private javax.swing.JTextField jTextPn;
    // End of variables declaration//GEN-END:variables
}
