/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ali
 */
public class NewJFrame_FORMULARIO2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame_FORMULARIO
     */
    public NewJFrame_FORMULARIO2() {
        initComponents();
        //CODIGO PARA CENTRAR LA PANTALLA
        this.setLocationRelativeTo(null);
        //codigo para acomodar la imagen
        ImageIcon fondo = new ImageIcon("src/arte-digital-martina-stipan-1.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(fondoo.getWidth(), fondoo.getHeight(),Image.SCALE_DEFAULT));
         fondoo.setIcon(icono);
           this.repaint();
           
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2apellidoM = new javax.swing.JLabel();
        jLabel2apellidopaterno = new javax.swing.JLabel();
        jLabel2nomb4 = new javax.swing.JLabel();
        jButton2salir = new javax.swing.JButton();
        fondoo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("datos del formulario");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 510, -1));

        jPanel5.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 130, 60));

        jLabel2apellidoM.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2apellidoM.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2apellidoM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 18))); // NOI18N
        getContentPane().add(jLabel2apellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 260, 60));

        jLabel2apellidopaterno.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2apellidopaterno.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2apellidopaterno.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 18))); // NOI18N
        getContentPane().add(jLabel2apellidopaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 260, 60));

        jLabel2nomb4.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2nomb4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2nomb4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 18))); // NOI18N
        getContentPane().add(jLabel2nomb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, 60));

        jButton2salir.setFont(new java.awt.Font("Kristen ITC", 1, 11)); // NOI18N
        jButton2salir.setText("Salir");
        jButton2salir.setOpaque(false);
        jButton2salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 99, 38));

        fondoo.setFont(new java.awt.Font("Kristen ITC", 0, 14)); // NOI18N
        fondoo.setForeground(new java.awt.Color(255, 255, 255));
        fondoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arte-digital-martina-stipan-1.jpg"))); // NOI18N
        fondoo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        getContentPane().add(fondoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2salirActionPerformed
          System.exit(0);  
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_FORMULARIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame_FORMULARIO2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoo;
    private javax.swing.JButton jButton2salir;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2apellidoM;
    public javax.swing.JLabel jLabel2apellidopaterno;
    public javax.swing.JLabel jLabel2nomb4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
