/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import javax.swing.JOptionPane;

/**
 *
 * @author ali
 */
public class NewJFrameACCESO extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameACCESO
     */
    public NewJFrameACCESO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2contrasenia = new javax.swing.JLabel();
        jLabel3usuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jToggleButton1entrar = new javax.swing.JToggleButton();
        jToggleButton2salir = new javax.swing.JToggleButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 24))); // NOI18N
        jPanel3.setLayout(null);

        jLabel2contrasenia.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel2contrasenia.setText("Contraceña");
        jPanel3.add(jLabel2contrasenia);
        jLabel2contrasenia.setBounds(16, 157, 92, 20);

        jLabel3usuario.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jLabel3usuario.setText("usuario");
        jPanel3.add(jLabel3usuario);
        jLabel3usuario.setBounds(16, 73, 58, 20);

        txtUsuario.setFont(new java.awt.Font("Kristen ITC", 1, 12)); // NOI18N
        jPanel3.add(txtUsuario);
        txtUsuario.setBounds(126, 72, 260, 40);

        jToggleButton1entrar.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jToggleButton1entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accept.png"))); // NOI18N
        jToggleButton1entrar.setText("Entrar");
        jToggleButton1entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1entrarMouseClicked(evt);
            }
        });
        jPanel3.add(jToggleButton1entrar);
        jToggleButton1entrar.setBounds(151, 271, 119, 41);

        jToggleButton2salir.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        jToggleButton2salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross.png"))); // NOI18N
        jToggleButton2salir.setText("salir");
        jPanel3.add(jToggleButton2salir);
        jToggleButton2salir.setBounds(288, 271, 101, 41);

        jPasswordField1.setText("jPasswordField1");
        jPanel3.add(jPasswordField1);
        jPasswordField1.setBounds(126, 158, 150, 20);

        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(-6, 0, 410, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1entrarMouseClicked
     String usuario ="admi";
      String contraseña = "isc";
       String pass = new String(jPasswordField1.getPassword()); 
       
        if (txtUsuario.getText().equals(usuario)&& pass.equals(contraseña)) {
            
            NewJFrame_FORMULARIO  formul = new NewJFrame_FORMULARIO ();
             formul.setVisible(true);
              dispose ();
         
        }
         else { 
            JOptionPane.showMessageDialog(this, "usuario / contraseña incorrecta");
            
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1entrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameACCESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameACCESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameACCESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameACCESO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameACCESO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2contrasenia;
    private javax.swing.JLabel jLabel3usuario;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JToggleButton jToggleButton1entrar;
    private javax.swing.JToggleButton jToggleButton2salir;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
